config/routes.rb
Rails.application.routes.draw do

  # Changing the default main page to the patient's index view
  get '/', to: 'patients#index'

  resources :patients, only: [:index] do
    get 'transfer'
  end

  # The about view (extra)
  get 'about', to: 'about#show'

end

app/models/admission.rb
class Admission < ApplicationRecord

  belongs_to :patient

  has_many :admission_diagnoses
  has_many :diagnoses, through: :admission_diagnoses

  has_many :admission_symptoms
  has_many :symptoms, through: :admission_symptoms

  has_many :observations

end

app/models/admission_diagnosis.rb
class AdmissionDiagnosis < ApplicationRecord

  belongs_to :admission
  belongs_to :diagnosis

end

app/models/admission_symptom.rb
class AdmissionSymptom < ApplicationRecord

  belongs_to :admission
  belongs_to :symptom

end

app/models/allergy.rb
class Allergy < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord

  def described_code
    "#{description} (#{code})"
  end

end

app/models/diagnostic_procedure.rb
class DiagnosticProcedure < ApplicationRecord

  belongs_to :patient

  def described_procedure
    "#{description} at #{moment.strftime("%-I:%M %p")}"
  end

end

app/models/facility.rb
class Facility < ApplicationRecord

end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord

  # UNIT RESTRICTION
  #
  # USING ENUM:
  MassUnit = [:mg]
  enum unit: MassUnit
  #
  #OR PLAIN STRING
  # MassUnit = [:mg]
  # validates :unit, inclusion: {in: MassUnit}


  # ROUTE RESTRICTION
  #
  # USING ENUM:
  MedicationRoute = [:PO, :IM, :SC]
  enum route: MedicationRoute
  #
  #OR PLAIN STRING
  # MedicationRoute = [:PO, :IM, :SC]
  # validates :route, inclusion: {in: MedicationRoute}

  belongs_to :patient

  belongs_to :order_frequency

  def detailed_description
    "#{name} #{dosage.round}#{unit} #{route} q#{order_frequency.value}#{order_frequency.unit === 'hour' ? 'hr' : order_frequency.unit} to #{necessity}"
  end

end

app/models/observation.rb
class Observation < ApplicationRecord

  belongs_to :admission

end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord

  # UNIT RESTRICTION
  #
  # USING ENUM:
  FrequencyUnit = [:hour]
  enum unit: FrequencyUnit
  #
  #OR PLAIN STRING
  # FrequencyUnit = [:hour]
  # validates :unit, inclusion: {in: FrequencyUnit}

end

app/models/patient.rb
class Patient < ApplicationRecord

  # GENDER RESTRICTION
  #
  # USING ENUM:
  GENDERS = [:male, :female, :other]
  enum gender: GENDERS
  #
  #OR PLAIN STRING
  # GENDERS = [:male, :female, :other]
  # validates :gender, inclusion: {in: GENDERS}

  has_many :patient_allergies
  has_many :allergies, through: :patient_allergies

  has_many :medications, class_name: 'MedicationOrder'

  has_many :diagnostic_procedures

  has_many :patient_treatments
  has_many :treatments, through: :patient_treatments

  # Used for the diagnosis list of the 1st paragraph
  has_one :admission

  # Used for the diagnosis list of the 2nd paragraph (chronic_conditions = chronic_diagnosis)
  has_many :patient_chronic_conditions
  has_many :chronic_conditions, through: :patient_chronic_conditions, class_name: 'Diagnosis', source: :diagnosis

  # Used for the diagnosis list of the 3rd paragraph. Diagnoses obtained on the facility
  has_many :patient_diagnoses
  has_many :diagnoses, through: :patient_diagnoses

end

app/models/patient_allergy.rb
class PatientAllergy < ApplicationRecord

  belongs_to :patient
  belongs_to :allergy

end

app/models/patient_diagnosis.rb
class PatientDiagnosis < ApplicationRecord

  # Used for the diagnosis list in the 3rd paragraph
  belongs_to :patient
  belongs_to :diagnosis

end

app/models/patient_treatment.rb
class PatientTreatment < ApplicationRecord

  belongs_to :patient
  belongs_to :treatment

end

app/models/symptom.rb
class Symptom < ApplicationRecord

end

app/models/treatment.rb
class Treatment < ApplicationRecord

  def described_necessity
    "#{description} to #{necessity}"
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  # I set a callback to be executed before each actions that needs it (show only in this case)
  before_action :set_patient, only: [:transfer]

  # ********************************************************************************************************************
  # *                                           *** R E N D E R ***                                                    *
  # ********************************************************************************************************************

  # Shows the index view, with the list of all the Patients in the DB
  def index
    # I store in a variable all the Patients in the DB
    @patients = Patient.all
  end

  # Shows the show view, with all the data of one selected Patient
  def transfer
    # I search the facility and it's sended also to the transfer view
    @facility = Facility.first
  end

  private

  # Implementation of the Callback set_patient, to be executed  before each actions that needs it (show only in this case)
  def set_patient
    # It search the Patient in the DB by using the patient_id that it is receiving
    @patient = Patient.find params[:patient_id]
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeting_helper.rb
module GreetingHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/index.html.erb
<div class="card bg-light text-dark">

  <div class="card-header">
    <div class="d-flex justify-content-between align-items-end">
      <h3 class="pb-1">Patients</h3>
    </div>
  </div>

  <div class="card-body">

    <!-- Table -->
    <div id="div_tabla_id" class="div_tabla">

      <table id="tbl_id" cellspacing="0" cellpadding="0" class="standard-light-blue" style="width: 100%;">

        <thead>
        <tr style="text-align: left;">
        </tr>
        </thead>

        <tbody>

        <tr>
          <th>ID</th>
          <th>First name</th>
          <th>Last name</th>
          <th>MR</th>
          <th>DOB</th>
          <th>Gender</th>
          <th>Age</th>
          <th></th>
          </th>
        </tr>

        <% @patients.each do |patient| %>
          <tr>
            <td style="text-align: center;">
              <%= patient.id %>
            </td>

            <td style="text-align: center;">
              <%= patient.first_name %>
            </td>

            <td style="text-align: left;">
              <%= patient.last_name %>
            </td>

            <td style="text-align: center;">
              <%= patient.mr %>
            </td>

            <td style="text-align: center;">
              <%= patient.dob.year %>
            </td>

            <td style="text-align: center;">
              <%= patient.gender %>
            </td>

            <td style="text-align: center;">
              <%= (Time.now.year - patient.dob.year) %>
            </td>

            <td>
              <%= link_to patient_transfer_path(patient), class: 'btn btn-primary btn-sm faa-parent animated-hover' do %>
                <i class="fa fa-arrow-right faa-horizontal faa-slow"></i>
              <% end %>
            </td>
          </tr>
        <% end %>

        </tbody>

        <tfoot>
        <tr>
        </tr>
        </tfoot>

      </table>

    </div>

  </div>

</div>

app/views/patients/transfer.html.erb
<div class="card bg-light text-dark">

  <div class="card-header" style="padding: 5px">
    <h3 class="pb-1">Emergency Transfer Summary (Form 34L-D)</h3>
  </div>

  <div class="card-body" style="padding: 0px">


    <div class="card" style="padding: 5px">
      <h4 class="card-title pb-1">Transferring Facility</h4>
    </div>

    <div class="card" style="padding: 0px">
      <div class="row" style="padding-left: 5px">
        <div class="col-3" style="border-right: 1px solid #DFDFDF">
          <b>Name</b>
          <br>
          <%= @facility.name %>
        </div>
        <div class="col-9" style="border-left: 1px solid #DFDFDF"></div>
      </div>
    </div>

    <div class="card" style="padding: 5px">
      <h4 class="card-title pb-1">Patient Information</h4>
    </div>

    <div class="card" style="padding: 0px">
      <div class="row" style="padding-left: 5px">
        <div class="col-3" style="border-right: 1px solid #DFDFDF;">
          <b>First Name</b>
          <br>
          <%= @patient.first_name %>
        </div>
        <div class="col-2" style="border-right: 1px solid #DFDFDF; border-left: 1px solid #DFDFDF;">
          <b>Middle Name</b>
          <br>
          <%= @patient.middle_name %>
        </div>
        <div class="col-2" style="border-right: 1px solid #DFDFDF; border-left: 1px solid #DFDFDF;">
          <b>Last Name</b>
          <br>
          <%= @patient.last_name %>
        </div>
        <div class="col-2" style="border-right: 1px solid #DFDFDF; border-left: 1px solid #DFDFDF;">
          <b>
            Medical Record
            (MR)
          </b>
          <br>
          <%= @patient.mr %>
        </div>

        <div class="col-3" style="border-left: 1px solid #DFDFDF"></div>
      </div>
    </div>

    <div class="card" style="padding-left: 5px; padding-right: 5px">

      <h4 class="card-title">Summary</h4>

      <p style="text-align: justify">
        This <%= (Time.now.year - @patient.dob.year) %> years old <%= @patient.gender %>
        was admitted to <%= @facility.name %> emergency facility
        on <%= @patient.admission.moment.strftime("%B, %d, %Y") %>,
        at <%= @patient.admission.moment.strftime("%-I:%M %p") %> due to

        <!-- {{patient.admission.diagnoses described_code | comma_separate}} OK -->
        <%= @patient.admission.diagnoses.map(&:described_code).to_sentence %>. The observed symptoms on admission were
        <%= @patient.admission.symptoms.map(&:description).to_sentence %>.
        <%= @patient.admission.observations.map(&:description).to_sentence %>.
      </p>

      <p style="text-align: justify">
        Upon asking about known allergies, the patient disclosed
        <%= @patient.allergies.map(&:description).to_sentence %>. Upon asking about chronic conditions, the patient
        disclosed

        <!-- {{patient.chronic_conditions > described_code | comma_separated}}-->
        <%= @patient.chronic_conditions.map(&:described_code).to_sentence %>.
        The patient was administered with
        <%= @patient.medications.map(&:detailed_description).to_sentence %>.
      </p>

      <p style="text-align: justify">
        The staff performed <%= @patient.diagnostic_procedures.map(&:described_procedure).to_sentence %>,
        revealing

        <!-- {{patient.diagnoses > described_code | comma_separate}} -->
        <%= @patient.diagnoses.map(&:described_code).to_sentence %>. Our team proceeded to
        <%= @patient.treatments.map(&:described_necessity).to_sentence %>.
      </p>

    </div>

  </div>

  <div class="card-footer d-print-none">
    <p>
      <a class="btn btn-default btn-danger faa-parent animated-hover" style="text-decoration: none;" href="<%= patients_path %>">
        <i class="fa fa-arrow-left faa-horizontal fa-fast"></i>
        Go back
      </a>

      <button class="btn btn-default btn-info faa-parent animated-hover" style="text-decoration: none;" onclick="window.print()">
        <i class="fa fa-print faa-horizontal fa-fast"></i>
        &nbsp;&nbsp;Print&nbsp;&nbsp;&nbsp;&nbsp;
      </button>
    </p>

  </div>

</div>