config/routes.rb
Rails.application.routes.draw do

  # Changing the default main page to the patient's index view
  get '/', to: 'patients#index'

  resources :patients, only: [:index] do
    get 'transfer'
  end

  # The about view (extra)
  get 'about', to: 'about#show'

end

app/models/admission.rb
class Admission < ApplicationRecord

  belongs_to :patient

  has_many :admission_diagnoses
  has_many :diagnoses, through: :admission_diagnoses

  has_many :admission_symptoms
  has_many :symptoms, through: :admission_symptoms

  has_many :observations

end

app/models/admission_symptom.rb
class AdmissionSymptom < ApplicationRecord

  belongs_to :admission
  belongs_to :symptom

end

app/models/allergy.rb
class Allergy < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord

  def described_code
    "#{description} (#{code})"
  end

end

app/models/facility.rb
class Facility < ApplicationRecord

end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord

  # UNIT RESTRICTION
  #
  # USING ENUM:
  MassUnit = [:mg]
  enum unit: MassUnit
  #
  #OR PLAIN STRING
  # MassUnit = [:mg]
  # validates :unit, inclusion: {in: MassUnit}


  # ROUTE RESTRICTION
  #
  # USING ENUM:
  MedicationRoute = [:PO, :IM, :SC]
  enum route: MedicationRoute
  #
  #OR PLAIN STRING
  # MedicationRoute = [:PO, :IM, :SC]
  # validates :route, inclusion: {in: MedicationRoute}

  belongs_to :patient

  belongs_to :order_frequency

  def detailed_description
    "#{name} #{dosage.round}#{unit} #{route} q#{order_frequency.value}#{order_frequency.unit === 'hour' ? 'hr' : order_frequency.unit} to #{necessity}"
  end

end

app/models/observation.rb
class Observation < ApplicationRecord

  belongs_to :admission

end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord

  # UNIT RESTRICTION
  #
  # USING ENUM:
  FrequencyUnit = [:hour]
  enum unit: FrequencyUnit
  #
  #OR PLAIN STRING
  # FrequencyUnit = [:hour]
  # validates :unit, inclusion: {in: FrequencyUnit}

end

app/models/patient.rb
class Patient < ApplicationRecord

  # GENDER RESTRICTION
  #
  # USING ENUM:
  GENDERS = [:male, :female, :other]
  enum gender: GENDERS
  #
  #OR PLAIN STRING
  # GENDERS = [:male, :female, :other]
  # validates :gender, inclusion: {in: GENDERS}

  has_many :patient_allergies
  has_many :allergies, through: :patient_allergies

  has_many :medications, class_name: 'MedicationOrder'

  has_many :diagnostic_procedures

  has_many :patient_treatments
  has_many :treatments, through: :patient_treatments

  # Used for the diagnosis list of the 1st paragraph
  has_one :admission

  # Used for the diagnosis list of the 2nd paragraph (chronic_conditions = chronic_diagnosis)
  has_many :patient_chronic_conditions
  has_many :chronic_conditions, through: :patient_chronic_conditions, class_name: 'Diagnosis', source: :diagnosis

  # Used for the diagnosis list of the 3rd paragraph. Diagnoses obtained on the facility
  has_many :patient_diagnoses
  has_many :diagnoses, through: :patient_diagnoses

end

app/models/patient_allergy.rb
class PatientAllergy < ApplicationRecord

  belongs_to :patient
  belongs_to :allergy

end

app/models/patient_diagnosis.rb
class PatientDiagnosis < ApplicationRecord

  # Used for the diagnosis list in the 3rd paragraph
  belongs_to :patient
  belongs_to :diagnosis

end

app/models/patient_treatment.rb
class PatientTreatment < ApplicationRecord

  belongs_to :patient
  belongs_to :treatment

end

app/models/symptom.rb
class Symptom < ApplicationRecord

end

app/models/treatment.rb
class Treatment < ApplicationRecord

  def described_necessity
    "#{description} to #{necessity}"
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeting_helper.rb
module GreetingHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'logos/saint_bernard_face_165X165.png' %>

  <title>Saint Bernard Emergency Transfer</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap core CSS for display rendering -->
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" %>

  <!-- Bootstrap core CSS for printing -->
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css", media: 'print' %>

  <!-- Font Awesome Core -->
  <%= stylesheet_link_tag "font-awesome-4.7.0/css/font-awesome" %>

  <!-- Alertify: includes the core style -->
  <%= stylesheet_link_tag "alertifyjs/css/alertify.min" %>

  <!-- Alertify: include a theme (default theme in this case) -->
  <%= stylesheet_link_tag "alertifyjs/css/themes/default.min" %>

  <!-- Font Awesome Animated Icons -->
  <%= stylesheet_link_tag "font-awesome-animation" %>

  <!-- Custom General Style for the app  -->
  <%= stylesheet_link_tag "general_style" %>

  <!-- Custom styles for the Sticky footer navbar -->
  <%= stylesheet_link_tag "sticky-footer-navbar" %>

  <!-- Custom table styles for the tables -->
  <%= stylesheet_link_tag "tablesStyles" %>

  <!-- Custom style for the Checkboxes -->
  <%= stylesheet_link_tag "checkbox_style" %>

  <!--  pretty checkbox CDN, A pure CSS library to beautify checkbox and radio buttons!-->
  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css" %>

</head>

<body>

<header>
  <!-- Fixed Navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

    <a class="navbar-brand  faa-parent animated-hover" href="<%= patients_path %>">
      <%= image_tag 'logos/saint_bernard_chest_274X274.png', width: '40px', height: '40px', class: 'fa faa-flash fa-fast' %>
      Saint Bernard Transfer
    </a>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active" style="margin-left: 15px; text-decoration: none">
          <a href="<%= patients_path %>" class="nav-link faa-parent animated-hover">
            <%= image_tag 'icons/patients_female_and_male_64X64_16bit.png', width: '24px', height: '24px', class: 'fa faa-ring fa-slow' %>
            Patients
          </a>
        </li>

        <li class="nav-item active" style="margin-left: 20px; text-decoration: none">
          <%= link_to about_path, class: "nav-link faa-parent animated-hover" do %>
            <%= image_tag 'icons/About-me-icon_32X32.png', width: '24px', height: '24px', class: 'fa faa-ring fa-slow' %>
            About
          <% end %>
        </li>
      </ul>
    </div>

  </nav>
  <!-- / Fixed Navbar -->
</header>

<!-- Page content -->
<main class="container">
  <div class="row mt-3">
    <div class="content col-12" style="padding: 0">
      <%= yield %>
    </div>
  </div>
</main>
<!-- / Page content -->

<!-- Page Footer -->
<footer class="footer">
  <div class="container">
    <a href="http://reiniergarcia.com" style="text-decoration: none; left: 200px !important;">
            <span class="text-muted faa-parent animated-hover">
                <span class="fa fa-copyright faa-ring fa-slow"></span> All Copyrights Reserved Reinier Garcia: <%= Time.now.strftime("%Y") %>
            </span>
    </a>
  </div>
</footer>
<!-- / Page Footer -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js' %>

<%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' %>

<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js' %>

<!-- ** JavaScript file for the Alertify Plugin  ** -->
<script type="text/javascript" src="alertifyjs/alertify.min.js"></script>


<!-- Application JavaScript Files
================================================== -->
<!--<script src="application.js"></script>-->
<%= javascript_include_tag 'application.js' %>


</body>
</html>

app/views/layouts/original_appplication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saint Bernard Emergency Transfer</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <%= yield %>
</div>
</body>

</html>